
DROP TABLE IF EXISTS USER ;
CREATE TABLE USER (email_USER NUMERIC(30) AUTO_INCREMENT NOT NULL,
password VARCHAR(50),
name VARCHAR(50),
surname VARCHAR(50),
name VARCHAR,
PRIMARY KEY (email_USER)) ENGINE=InnoDB; 

DROP TABLE IF EXISTS ANNONCE ;
CREATE TABLE ANNONCE (name_ANNONCE TEXT AUTO_INCREMENT NOT NULL,
image INT,
adresse TEXT,
description TEXT,
PRIMARY KEY (name_ANNONCE)) ENGINE=InnoDB;

ALTER TABLE USER ADD CONSTRAINT FK_USER_name_ANNONCE FOREIGN KEY (name_ANNONCE) REFERENCES ANNONCE (name_ANNONCE);